export type GenderType = 'male' | 'female';
export type StatusType = 'active' | 'inactive';

export interface CreateUserPayload {
    name: string;
    email: string;
    gender: GenderType;
    status: StatusType;
}

export interface UserResponse extends CreateUserPayload {
    id: number;          // Unique ID generated by the database
}